In [2]:
import numpy as np

In [ ]:
### Импортируйте библиотеку Numpy и дайте ей псевдоним np.
### Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
### Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. 
### Будем считать, что каждый столбец - это признак, а строка - наблюдение. 
### Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 
### Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [3]:
b = np.array([i for i in range(10)], dtype = float)

In [4]:
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
type(b)

numpy.ndarray

In [6]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [7]:
a.shape

(5, 2)

In [9]:
mean_a = a.mean(0)

In [10]:
print(mean_a)

[2.  8.4]


In [11]:
### Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
### содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. 
### Получившийся массив должен иметь размер 5x2.

In [12]:
aa = np.array([[mean_a[0], mean_a[1]],
              [mean_a[0], mean_a[1]],
              [mean_a[0], mean_a[1]],
              [mean_a[0], mean_a[1]],
              [mean_a[0], mean_a[1]]])
print(aa)

[[2.  8.4]
 [2.  8.4]
 [2.  8.4]
 [2.  8.4]
 [2.  8.4]]


In [13]:
a_centered = a - aa
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [14]:
### Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp.
### Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [15]:
a_centered_sp = a_centered[0:5, 0] @ a_centered[0:5, 1]
print(a_centered_sp)

8.0


In [16]:
observation = a.shape[0]
res = observation - 1
res = a_centered_sp / res
print(res)

2.0


In [17]:
### В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov.
### В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. 
### В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно
### элементу в строке с индексом 0 и столбце с индексом 1.

In [18]:
At = a.T
print(At)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [19]:
Res = np.cov(At)
print(Res)

[[1.  2. ]
 [2.  4.3]]


In [20]:
?np.cov

In [ ]:
### Тема “Работа с данными в Pandas”
### Задание 1
### Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами
### author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
### Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
### [1, 1, 1, 2, 2, 3, 3],
### ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
### [450, 300, 350, 500, 450, 370, 290].

In [21]:
import pandas as pd

In [22]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                  'author_name':['Тургенев', 'Чехов', 'Островский']},
                  columns=['author_id', 'author_name'])

In [23]:
print (authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [24]:
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                    'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]},
                    columns=['author_id', 'book_title', 'price'])

In [25]:
print(books)

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


In [26]:
print(books.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   author_id   7 non-null      int64 
 1   book_title  7 non-null      object
 2   price       7 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes
None


In [27]:
### Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [28]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')

In [29]:
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


In [30]:
### Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами

In [31]:
top5 = authors_price.copy()
top5 = top5.sort_values('price', ascending=False)
top5 = top5.head(5)
print(top5)

   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350


In [32]:
### top5 = top5.loc[top5['price'] > 349]
### print(top5)

In [33]:
### Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
### author_name, min_price, max_price и mean_price,
### в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.
au1 = authors_price.copy()
au1 = au1.query('author_name == "Тургенев"')
print(au1)
print(au1['price'].min())
print(au1['price'].max())
print(au1['price'].mean())

   author_id author_name         book_title  price
0          1    Тургенев        Отцы и дети    450
1          1    Тургенев              Рудин    300
2          1    Тургенев  Дворянское гнездо    350
300
450
366.6666666666667


In [37]:
min_price = au1['price'].min()
max_price = au1['price'].max()
mean_price = au1['price'].mean()
print(mean_ptice)

366.6666666666667


In [38]:
authors_stat = authors.copy()
authors_stat['min_price'] = 0
authors_stat['max_price'] = 0
authors_stat['mean_price'] = 0
print(authors_stat)

   author_id author_name  min_price  max_price  mean_price
0          1    Тургенев          0          0           0
1          2       Чехов          0          0           0
2          3  Островский          0          0           0


In [39]:
authors_stat.loc[(authors_stat['author_name']=='Тургенев'), 'min_price'] = min_price
authors_stat.loc[(authors_stat['author_name']=='Тургенев'), 'max_price'] = max_price
authors_stat.loc[(authors_stat['author_name']=='Тургенев'), 'mean_price'] = mean_price
print(authors_stat)

   author_id author_name  min_price  max_price  mean_price
0          1    Тургенев        300        450  366.666667
1          2       Чехов          0          0    0.000000
2          3  Островский          0          0    0.000000


In [40]:
au1 = authors_price.copy()
au1 = au1.query('author_name == "Чехов"')
### print(au1)
min_price = au1['price'].min()
max_price = au1['price'].max()
mean_price = au1['price'].mean()
authors_stat.loc[(authors_stat['author_name']=='Чехов'), 'min_price'] = min_price
authors_stat.loc[(authors_stat['author_name']=='Чехов'), 'max_price'] = max_price
authors_stat.loc[(authors_stat['author_name']=='Чехов'), 'mean_price'] = mean_price
print(authors_stat)

   author_id author_name        book_title  price
3          2       Чехов  Толстый и тонкий    500
4          2       Чехов   Дама с собачкой    450
   author_id author_name  min_price  max_price  mean_price
0          1    Тургенев        300        450  366.666667
1          2       Чехов        450        500  475.000000
2          3  Островский          0          0    0.000000


In [41]:
au1 = authors_price.copy()
au1 = au1.query('author_name == "Островский"')
### print(au1)
min_price = au1['price'].min()
max_price = au1['price'].max()
mean_price = au1['price'].mean()
authors_stat.loc[(authors_stat['author_name']=='Островский'), 'min_price'] = min_price
authors_stat.loc[(authors_stat['author_name']=='Островский'), 'max_price'] = max_price
authors_stat.loc[(authors_stat['author_name']=='Островский'), 'mean_price'] = mean_price
print(authors_stat)

   author_id author_name  min_price  max_price  mean_price
0          1    Тургенев        300        450  366.666667
1          2       Чехов        450        500  475.000000
2          3  Островский        290        370  330.000000


In [ ]:
### Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том,
### какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
### ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

In [43]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
print(authors_price)

   author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая


In [ ]:
### Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
### Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. 
### Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",
### а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, 
### при необходимости загрузите библиотеку Numpy.

In [44]:
? pd.pivot_table

In [47]:
table = pd.pivot_table(authors_price, values='price', index=['cover'], columns=['author_name'], aggfunc=np.sum)
print(table)

author_name  Островский  Тургенев  Чехов
cover                                   
мягкая            660.0     650.0    NaN
твердая             NaN     450.0  950.0
